package packageA

import "hechuqiu.github.io/gen-copier/test/packageB"

// Code generated by gen-copier; DO NOT EDIT.

func (source *TestSource) CopyTo(target *packageB.TestTarget) {
	target.Another = source.Other
	target.Name = source.Name
	target.Age = source.Age
}
